// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhQYQxQsmbQK_YCJgbNjpNfiJ3ZjXTIc',
    appId: '1:692565819169:web:d12b939a2443888af30860',
    messagingSenderId: '692565819169',
    projectId: 'gestao-estacionamentos-app',
    authDomain: 'gestao-estacionamentos-app.firebaseapp.com',
    storageBucket: 'gestao-estacionamentos-app.firebasestorage.app',
    measurementId: 'G-FTYPKH2T8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARcfXvckAlOel553xyAsCqa1v2tOS5J0',
    appId: '1:692565819169:android:9c7862faf5b80834f30860',
    messagingSenderId: '692565819169',
    projectId: 'gestao-estacionamentos-app',
    storageBucket: 'gestao-estacionamentos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoVpKgmK8nxqCtztRZwOjATs4XO_-pvzc',
    appId: '1:692565819169:ios:0a06037fda3c01a1f30860',
    messagingSenderId: '692565819169',
    projectId: 'gestao-estacionamentos-app',
    storageBucket: 'gestao-estacionamentos-app.firebasestorage.app',
    iosClientId: '692565819169-hji5i88mehtpq38a0u8r9945804pinor.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaoEstacionamentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoVpKgmK8nxqCtztRZwOjATs4XO_-pvzc',
    appId: '1:692565819169:ios:0a06037fda3c01a1f30860',
    messagingSenderId: '692565819169',
    projectId: 'gestao-estacionamentos-app',
    storageBucket: 'gestao-estacionamentos-app.firebasestorage.app',
    iosClientId: '692565819169-hji5i88mehtpq38a0u8r9945804pinor.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestaoEstacionamentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhQYQxQsmbQK_YCJgbNjpNfiJ3ZjXTIc',
    appId: '1:692565819169:web:028300a785eb9d13f30860',
    messagingSenderId: '692565819169',
    projectId: 'gestao-estacionamentos-app',
    authDomain: 'gestao-estacionamentos-app.firebaseapp.com',
    storageBucket: 'gestao-estacionamentos-app.firebasestorage.app',
    measurementId: 'G-NCPBTBLHCL',
  );
}
